### ISSUE TITLE
Crop Recommendation System

### ISSUE THREAD

**Issue by yogesh2598** [ashsid/CropProductionandPriceAnalysis#2]
A recommender model for crops.

**Comment by ashsid** [comment]
#The model below predicts 5 best crops that can be grown in AHMADABAD district of GUJRAT
#The code for the same:
data <- read.csv('crop_production.csv')
#reading the dataset

data$Yield <- data$Production / data$Area 
#creating a yield column 

state <- as.data.frame(subset(data, data$State_Name == "Gujarat"))

district <- subset(state, state$District_Name == "AHMADABAD")

train <- data.frame(district$Crop,district$Season,district$Yield)
#above three lines takes the required data to perform desired computations.

colnames(train) <- c("Crop", "Season", "Yield")//renaming the columns

rating <- dcast(train, Season~Crop , value.var ="Yield", fun.aggregate=mean)
#conversion to matrix with the required format for further computations.


rating2 <- as.matrix(rating[,-1])

ratingmat <- as(rating2, "realRatingMatrix")

ratingmat <- normalize(ratingmat) 
#final rating matrix

**Comment by ashsid** [comment]
Please review the recommendation system code so that the above issue can be closed.

**Comment by ashsid** [comment]
Final Changes made, Fully updated.
