### ISSUE TITLE
Visualisation of the rainfall dataset

### ISSUE THREAD

**Issue by yogesh2598** [ashsid/CropProductionandPriceAnalysis#3]
Interactive plots for the rainfall dataset.

**Comment by AnmolGarg2002** [comment]
There are currently three ways to visualize the rainfall data.

1.  You can see a graph of annual rainfall over the years for a Geographic region.
2.   A animated graph of monthly rainfall over the years with the average rainfall over the years for a Geographic region.
3.   A bar graph which shows average rainfall of Geographic regions.
